config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :pictures
=======
  resources :users
>>>>>>> 60137d1631d9e096f44edfc85d5b0769d16fbc35
  resources :reviews
  resources :products
  resources :charges

  post '/search' => 'products#search'

  root 'welcome#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  include ActiveModel::Validations
  validates :first_name, :last_name, :address,  :city, :state, :zip_code, presence: :true #:credit_card_type,
  # validates :credit_card, numericality: { only_integer: true}, length: { minimum: 16, maximum: 16 }
  validates :email, uniqueness: true, presence: :true, confirmation: true, email: true
  validates :email_confirmation, presence: true
  validates_with  AgeValidator

  has_many :products

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :email_confirmation, :birthday, :address, :city, :state, :zip_code, :credit_card_type, :credit_card)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
<div class="container">
  <% if @user.errors.any? %>
  <div class= "container" id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
      <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :email_confirmation %>
    <%= f.text_field :email_confirmation %>
  </div>
  <div class="field">
    <%= f.label :birthday %>
    <%= f.date_field :birthday, start_year: 1930  %>
  </div>
</div>
<div class="container">
  <div class="field">
    <%= f.label :address %>
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip_code %>
    <%= f.text_field :zip_code %>
  </div>
 
  <div class="actions">
    <%= f.submit %>
  </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Birthday</th>
      <th>Address</th>
      <th>City</th>
      <th>State</th>
      <th>Zip Code</th>
      <th>Credit Card Type</th>
      <th>Credit Card</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= user.birthday %></td>
        <td><%= user.address %></td>
        <td><%= user.city %></td>
        <td><%= user.state %></td>
        <td><%= user.zip_code %></td>
        <td><%= user.credit_card_type %></td>
        <td><%= user.credit_card %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<div class="container new_user">
<h1>New Wyncoholic</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', products_path, class: "btn btn-info" %>
</div>

app/views/users/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h2>Customer Account Information</h2><br>

<p>
  <strong>First Name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last Name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @user.birthday %>
</p>

<p>
  <strong>Address:</strong>
  <%= @user.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @user.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @user.state %>
</p>

<p>
  <strong>Zip Code:</strong>
  <%= @user.zip_code %>
</p>

<%= link_to 'Edit', edit_user_path(@user), class: "btn btn-info" %> |
<%= link_to 'Start Shopping', products_path(@products), class: "btn btn-info" %>
</div>