config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :pictures
=======
  resources :users
>>>>>>> 60137d1631d9e096f44edfc85d5b0769d16fbc35
  resources :reviews
  resources :products
  resources :charges

  post '/search' => 'products#search'

  root 'welcome#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :description, :name, presence: :true
	validates :price_in_cents, numericality: { only_integer: true, greater_than: 0 }
	has_many :reviews
<<<<<<< HEAD
	has_one :picture
=======
  belongs_to :user
  
>>>>>>> 60137d1631d9e096f44edfc85d5b0769d16fbc35
	
	def formatted_price
		price_in_dollars = price_in_cents.to_f / 100
		format( "$%.2f", price_in_dollars )
	end
end
 

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

 # GET /products/1
 #  GET /products/1.json
  def show
    @review = Review.new
  end

  # GET /products/new
  def new
    @product = Product.new
  end

   # GET /products/1/edit
  def edit
  end

  def search
    @products = Product.where(name: params['term'])
    render :index
  end

   # POST /products
   # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

   # PATCH/PUT /products/1
   # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

   # DELETE /products/1
   # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :price_in_cents, :url, :user_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price_in_cents %><br>
    <%= f.number_field :price_in_cents %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Alcohol Selection</h1>

<div class="container search">
<%= form_tag '/search' do %>
  <%= search_field_tag :term %>
  <%= submit_tag 'Search' %>
<% end %>
</div>

<table class="table talbe-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
<<<<<<< HEAD
      <th>image</th>
=======
      <th>Quantity</th>
      <th>Picture</th>
>>>>>>> 60137d1631d9e096f44edfc85d5b0769d16fbc35
      <th colspan="3"></th>
    </tr>
  </thead>
  <%= link_to 'View Cart', charges_path, class: "btn btn-info cart" %> 
  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.formatted_price %></td>
<<<<<<< HEAD
        <td><%= product.picture.url %></td>image_tag 
=======
        <td><%= number_field :user, :id %></td>
        <td><%= image_tag product.url %></td>
        <td><%= link_to 'Add to Cart', products_path, class: "btn btn-info", method: :get, data: {confirm: 'Are you sure you want to add this to your cart?' } %></td>
>>>>>>> 60137d1631d9e096f44edfc85d5b0769d16fbc35
        <td><%= link_to 'Show', product, class: "btn btn-info" %></td>
        <!-- <td><%= link_to 'Edit', edit_product_path(product), class: "btn btn-info" %></td>
        <td><%= link_to 'Destroy', product, class: "btn btn-info", method: :delete, data: { confirm: 'Are you sure?' } %></td>  -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<!-- <%= link_to 'New Product', new_product_path %> -->

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.formatted_price %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag @product.url %>
</p>


<h3>Reviews</h3>

<% @product.reviews.each do |review| %>
  <p>
    <%= review.comment %>
    <br>
    Created: <%= time_ago_in_words review.created_at %> ago
  </p>
<% end %>

<h3>New Review</h3>
<%= render 'reviews/form' %>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>