config/routes.rb
Rails.application.routes.draw do
<<<<<<< HEAD
  resources :pictures
=======
  resources :users
>>>>>>> 60137d1631d9e096f44edfc85d5b0769d16fbc35
  resources :reviews
  resources :products
  resources :charges

  post '/search' => 'products#search'

  root 'welcome#index'

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
def new
end

def create
	# Amount in cents
	@amount = 1500

	customer = Stripe::Customer.create(
		:email => 'example@stripe.com', 
		:card => params[:stripeToken])

	charge = Stripe::Charge.create(
		:customer => customer.id,
		:amount => @amount,
		:description => 'Rails Stripe customer', 
		:currency => 'usd'
		)

rescue Stripe::CardError => e 
	flash[:error] = e.message
	redirect_to charges_path
end
	
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/create.html.erb
<div class="container confirm">
<h2>Thanks, you paid<strong> $15.00</strong>!</h2>
<h3>Your order is on the way!</h3>

<img src="/assets/lab.png" alt="The Lab Miami">
</div>

app/views/charges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Cart</h1>

<h2>Products</h2>

<table class="table talbe-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% Product.find(1) do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.formatted_price %></td>
        <td>3</td>
        <td><%= image_tag product.url %></td>
        <td><%= link_to 'Edit', edit_product_path(product), class: "btn btn-info" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Continue Shopping', products_path, class: "btn btn-info" %> <br> <br>
<%= link_to  'Check out', new_charge_path, class: "btn btn-info" %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
<div class="container checkout">
<div class="container">
  <article>
    <label class="amount">
      <h2><span>Amount: $15.00</span></h2>
    </label>
  </article>
  </div>


<form action="" method="POST">
  <script
    src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.application.secrets.stripe_publishable_key %>"
    data-amount="1500"
    data-name="Wyncohol Order"
    data-description="3 Wynwood Beers ($15.00)"
    data-locale="auto">
  </script>
</form>

<% end %>
</div>